# Site Settings
name: Rahul Chandra | Gameplay & UI Programmer
title: Rahul Chandra | Gameplay & UI Programmer
description: Gameplay, UI, and Tools Programmer Portfolio
tags:
  - portfolio
  - gameplay programmer
  - ui programmer
  - tools
  - unreal engine
  - unity
show_hero: true
menu:
  - title: Home
    url: /
  - title: Gameplay Programmer Projects
    url: /gameplay-projects
  - title: UI Programmer Projects
    url: /ui-projects
email: rahulchandra99@gmail.com

# Social Media Settings
github_username: RahulChandra99
linkedin_username: rahulchandra99
youtube_username: rahulchandra4125
itchio_username: rahul-chandra

# Posts Settings
show_time_bar: false
show_modal_on_exit: false
show_modal_on_finish_post: false
two_columns_layout: false

# Advanced Settings
baseurl: "" # For GitHub Pages
url: "https://rahulchandra99.github.io"
google_analytics: "" # Optional
language: "en"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate

# Exclude unnecessary files
exclude: [
  'vendor/',
  'LICENSE',
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]
