# Site Settings
name: Rahul Chandra | Gameplay & UI Programmer
title: Rahul Chandra | Gameplay & UI Programmer
description: Gameplay, UI, and Tools Programmer Portfolio
tags:
  - portfolio
  - gameplay programmer
  - ui programmer
  - tools
  - unreal engine
  - unity
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Gameplay Programmer Projects
    url: /gameplay-projects
  - title: UI Programmer Projects
    url: /ui-projects
email: rahul.yourmail@example.com
disqus_username: # Leave empty to disable comments
formspree_form_id: # Optional, from https://formspree.io (leave empty if not using)

# Social Media Settings
github_username: RahulChandra99
linkedin_username: rahulchandra99

# Posts Settings (Clean and simple)
show_time_bar: false
show_modal_on_exit: false
show_modal_on_finish_post: false
two_columns_layout: false

# Advanced Settings
baseurl: "" # For GitHub Pages
url: "https://yourusername.github.io"
google_analytics: "" # Optional
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Content paginator (disabled)
paginate_content:
  enabled: false

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate

# Exclude unnecessary files
exclude: [
  'docs/',
  'vendor/',
  'LICENSE',
  'CHANGELOG.md',
  'jekflix.gemspec',
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]
